name: Code Coverage

on: [push, pull_request]

jobs:
  backend:
    name: Generate Jacoco Test Report - Back
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Test Backend
        run: |
          cd ./back
          mvn clean test

      - name: Generate Jacoco Report
        run: |
          cd ./back
          mvn jacoco:report
          
      - name: Commit Jacoco Report
        run: |
          git config --global user.email "hlml200294@gmail.com"
          git config --global user.name "Hugo-LML"
          git fetch --all
          git checkout develop
          git pull
          git add target/site
          git commit -m 'feat(coverage): jacoco report added'
          git push

  frontend:
    name: Run Coverage Tests - Front
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          cd ./front
          npm i

      - name: Run Coverage Tests
        run: |
          cd ./front
          npm run test-coverage

      - name: Commit Coverage Report 
        run: |
          git config --global user.email "hlml200294@gmail.com"
          git config --global user.name "Hugo-LML"
          git fetch --all
          git checkout develop
          git pull
          git add coverage/bobapp
          git commit -m 'feat(coverage): coverage report added'
          git push
